import { CROSS_APP_API_PATHS } from '@hopehub/clinic-api/cross-app-api-paths.constants';

export const API_PATHS = {
  CONSULTATIONS: '/consultations',
  BILLING_PLANS: '/billing/plans',
  PAYMENTS: {
    CREATE_ORDER: (consultationId: string) => `/payments/${consultationId}/create-order`,
    VERIFY: (consultationId: string) => `/payments/${consultationId}/verify`,
  },
  PATIENT: {
    PRESCRIPTIONS: '/patient/prescriptions',
    PRESCRIPTION_PDF: (id: string) => `/patient/prescriptions/${id}/pdf`,
    PRESCRIPTION_SHARE: (id: string) => `/patient/prescriptions/${id}/share`,
    TODAY_DOSES: '/patient/today-doses',
    DOSE_HISTORY: '/patient/dose-history',
    MEDICINE_REMINDERS: '/patient/medicine-reminders',
    DOSE_TAKE: (id: string) => `/patient/dose-events/${id}/take`,
    DOSE_SKIP: (id: string) => `/patient/dose-events/${id}/skip`,
    DOSE_SNOOZE: (id: string) => `/patient/dose-events/${id}/snooze`,
    DOSE_EXPLAIN: (id: string) => `/patient/dose-events/${id}/explain`,
    REMINDER_PREFERENCES: '/patient/reminder-preferences',
    PROFILE: '/patient/profile',
    PROFILE_IMAGE: '/me/profile-image',
    CLINICAL_MEDIA: '/patient/clinical-media',
    CLINICAL_MEDIA_ITEM: (id: string) => `/patient/clinical-media/${id}`,
    CLINICAL_MEDIA_AI_PREVIEW: (id: string) => `/patient/clinical-media/${id}/ai-preview`,
    CLINICAL_MEDIA_META: '/clinical-media/meta',
    CLINICAL_MEDIA_FILE: (id: string) => `/clinical-media/${id}/file`,
    ADDRESSES: '/patient/addresses',
    ADDRESS: (id: string) => `/patient/addresses/${id}`,
    ADDRESS_DEFAULT: (id: string) => `/patient/addresses/${id}/default`,
    PROFILE_PASSWORD: '/patient/profile/password',
    CARD: '/patient/card',
    LAB_RESULTS: '/patient/lab-results',
    REFERRALS_SUMMARY: CROSS_APP_API_PATHS.PATIENT.REFERRALS_SUMMARY,
    REWARDS: CROSS_APP_API_PATHS.PATIENT.REWARDS,
    REWARDS_CHECKOUT_QUOTE: CROSS_APP_API_PATHS.PATIENT.REWARDS_CHECKOUT_QUOTE,
    DELIVERIES: '/patient/deliveries',
    DELIVERY: (id: string) => `/patient/deliveries/${id}`,
  },
  ADMIN: {
    DOCTORS: '/admin/doctors',
    REPORTS: '/admin/reports',
  },
  ANALYTICS: {
    EVENTS: '/analytics/events',
  },
  CHAT: {
    START: '/chat/start',
    SESSION: (id: string) => `/chat/${id}`,
    MESSAGE: (id: string) => `/chat/${id}/message`,
    LINK: (id: string) => `/chat/${id}/link`,
  },
  VACANCIES: '/vacancies',
  PROVIDERS: '/providers',
  DOCTORS: '/providers',
  TESTIMONIALS: '/testimonials',
  FAQ: '/faq',
  BLOG: '/blog',
  BLOG_MOST_VIEWED: '/blog/most-viewed',
  BLOG_POST: (slug: string) => `/blog/${encodeURIComponent(slug)}`,
  BLOG_COMMENTS: (slug: string) => `/blog/${encodeURIComponent(slug)}/comments`,
  ONLINE_PROVIDERS: '/online-providers',
  ONLINE_DOCTORS: '/online-providers',
  RTC_ICE_SERVERS: '/rtc/ice-servers',
  DISEASES: '/diseases',
  CLINICS: '/clinics',
  PUBLIC_CONFIG: '/public-config',
  PUBLIC_PAGES: '/public-pages',
  PUBLIC_PAGE: (slug: string) => `/public-pages/${encodeURIComponent(slug)}`,
} as const;
