export const ROUTE_PATHS = {
  LOGIN: 'login',
  ABOUT: 'about',
  TREATMENTS: 'treatments',
  CHRONIC_CARE: 'chronic-care',
  FAQ: 'faq',
  CONTACT: 'contact',
  SAFETY: 'safety',
  PRIVACY: 'privacy-policy',
  LEGAL: 'legal',
  TERMS: 'terms-and-conditions',
  RETURN_EXCHANGE: 'return-and-exchange-policy',
  SHIPPING: 'shipping-policy',
  PAYMENT: 'payment-policy',
  WHY_SUCCESSFUL: 'why-successful',
  OUR_DOCTORS: 'our-doctors',
  BLOG: 'blog',
  TESTIMONIALS: 'testimonials',
  CAREERS: 'careers',
  PATIENT_DASHBOARD: 'patient/dashboard',
  PATIENT_ACCOUNT: 'patient/account',
  PATIENT_ACCOUNT_PROFILE: 'patient/account/profile',
  PATIENT_ACCOUNT_ADDRESSES: 'patient/account/addresses',
  PATIENT_PROFILE: 'patient/profile',
  AUTH_RESET: 'auth/reset'
} as const;
