INSERT INTO "HopeHubOffering" (
  "id", "code", "slug", "title", "subtitle", "description", "type", "priceInPaise",
  "compareAtPriceInPaise", "discountEnabled", "discountType", "discountLabel", "discountCode",
  "discountPercent", "discountFlatInPaise", "discountMaxInPaise", "discountStartsAt",
  "discountEndsAt", "partialPaymentEnabled", "partialPaymentType", "partialPaymentLabel",
  "partialPaymentPercent", "partialPaymentFlatInPaise", "validityDays", "sessionCount",
  "sessionDurationMinutes", "deliveryMode", "ctaLabel", "routePath", "benefits", "audience",
  "metadata", "isActive", "isFeatured", "requiresLeadForm", "sortOrder", "updatedAt"
) VALUES (
  'hope-offer-recorded-wellness-session',
  'RECORDED_WELLNESS_SESSION',
  'recorded-wellness-session',
  'Recorded wellness session',
  'Audio, video, Telegram, and YouTube resources in one place.',
  'A sample recorded Hope Hub session entry. Admin can replace these links with Telegram group recordings, uploaded audio or video, and YouTube sessions.',
  'RECORDED_SESSION',
  NULL,
  NULL,
  false,
  'NONE',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  false,
  'NONE',
  NULL,
  NULL,
  NULL,
  NULL,
  1,
  NULL,
  'RECORDED',
  'Open resources',
  '/resources/recorded-wellness-session',
  ARRAY['Telegram group recordings', 'YouTube session support', 'Audio and video resource links'],
  ARRAY['Community members', 'People who missed a live session', 'Self-paced learners'],
  '{"mediaAccessMode":"PUBLIC","mediaAccessNote":"Replace these sample links from admin after uploading or pasting your real session media.","youtubeUrl":"https://www.youtube.com/","telegramGroupUrl":"https://t.me/"}'::jsonb,
  true,
  true,
  false,
  40,
  NOW()
)
ON CONFLICT ("id") DO UPDATE SET
  "title" = EXCLUDED."title",
  "subtitle" = EXCLUDED."subtitle",
  "description" = EXCLUDED."description",
  "type" = EXCLUDED."type",
  "deliveryMode" = EXCLUDED."deliveryMode",
  "ctaLabel" = EXCLUDED."ctaLabel",
  "routePath" = EXCLUDED."routePath",
  "benefits" = EXCLUDED."benefits",
  "audience" = EXCLUDED."audience",
  "metadata" = EXCLUDED."metadata",
  "isActive" = EXCLUDED."isActive",
  "isFeatured" = EXCLUDED."isFeatured",
  "sortOrder" = EXCLUDED."sortOrder",
  "updatedAt" = NOW();

INSERT INTO "HopeHubBanner" (
  "id", "title", "subtitle", "eyebrow", "ctaLabel", "routePath", "offeringId",
  "isActive", "sortOrder", "backgroundColor", "textColor", "updatedAt"
) VALUES (
  'hope-banner-recorded-sessions',
  'Recorded wellness sessions',
  'Audio, video, Telegram and YouTube resources for self-paced support.',
  'New resources',
  'Open recordings',
  '/resources/recorded-wellness-session',
  'hope-offer-recorded-wellness-session',
  true,
  4,
  '#f8fafc',
  '#0f172a',
  NOW()
)
ON CONFLICT ("id") DO UPDATE SET
  "title" = EXCLUDED."title",
  "subtitle" = EXCLUDED."subtitle",
  "eyebrow" = EXCLUDED."eyebrow",
  "ctaLabel" = EXCLUDED."ctaLabel",
  "routePath" = EXCLUDED."routePath",
  "offeringId" = EXCLUDED."offeringId",
  "isActive" = EXCLUDED."isActive",
  "sortOrder" = EXCLUDED."sortOrder",
  "backgroundColor" = EXCLUDED."backgroundColor",
  "textColor" = EXCLUDED."textColor",
  "updatedAt" = NOW();
