import { CROSS_APP_API_PATHS } from '@hopehub/clinic-api/cross-app-api-paths.constants';

export const API_PATHS = {
  AUTH: {
    STAFF_LOGIN: '/auth/staff-login',
    ME: '/me',
  },
  ADMIN: {
    REPORTS: '/admin/reports',
    AUDIT_LOGS: '/admin/audit-logs',
    AUTH_PROCESS_LOGS: '/admin/auth-process-logs',
    USERS: '/admin/users',
    USER_ROLE: (id: string) => `/admin/users/${id}/role`,
    USER_STATUS: (id: string) => `/admin/users/${id}/status`,
    ADMINS: '/admin/admins',
    ADMIN_STATUS: (id: string) => `/admin/admins/${id}/status`,
    TELEGRAM_BOTS: '/admin/telegram-bots',
    TELEGRAM_BOT_SETUP: (slug: string) => `/admin/telegram-bots/${slug}/setup`,
    TELEGRAM_BOTS_SETUP_ALL: '/admin/telegram-bots/setup-all',
    TELEGRAM_BOT_SESSION_UNLINK: (id: string) => `/admin/telegram-bots/sessions/${id}/unlink`,
    TELEGRAM_GROUP_HELP: '/admin/telegram-bots/group-help',
    TELEGRAM_GROUP_HELP_SEND: '/admin/telegram-bots/group-help/send',
    CONSULTATION_STATUS: (id: string) => `/admin/consultations/${id}/status`,
    SAFETY_FLAGS: '/admin/safety-flags',
    SAFETY_FLAG_NOTE: (consultationId: string) => `/admin/safety-flags/${consultationId}/notes`,
    ADHERENCE_RISK: '/admin/adherence/risk-cohorts',
    ANALYTICS_FUNNELS: '/admin/analytics/funnels',
    ANALYTICS_HOPE_HUB: '/admin/analytics/hope-hub',
    PAYMENTS: '/admin/payments',
    DONATIONS: '/admin/donations',
    FOLLOW_UPS: '/admin/follow-ups',
    FOLLOW_UP_BY_ID: (id: string) => `/admin/follow-ups/${id}`,
    PAYMENT_EVENTS: (id: string) => `/admin/payments/${id}/events`,
    PAYMENT_REFUND: (id: string) => `/admin/payments/${id}/refund`,
    DOCTORS: '/admin/doctors',
    DOCTORS_PENDING: '/admin/doctors/pending',
    CONSUMERS: '/admin/consumers',
    PATIENTS_SEARCH: '/admin/patients/search',
    PATIENTS: '/admin/patients',
    PURCHASE_ORDERS: '/admin/purchase-orders',
    SUPPLIERS: '/admin/suppliers',
    MEDICINES: '/admin/medicines',
    INVENTORY_OVERVIEW: '/admin/inventory/overview',
    INVENTORY_STORE_STOCK: (storeId: string) => `/admin/inventory/stores/${storeId}/stock`,
    NOTIFICATION_TEMPLATES: '/admin/notifications/templates',
    NOTIFICATION_BROADCAST: '/admin/notifications/broadcast',
    NOTIFICATION_BROADCASTS: '/admin/notifications/broadcasts',
    CONTACT_MAIL: '/admin/contact-mail',
    CONTACT_MAIL_BY_ID: (id: string) => `/admin/contact-mail/${id}`,
    CONTACT_MAIL_REPLY: (id: string) => `/admin/contact-mail/${id}/reply`,
    AUDIT_RETENTION_STATS: '/admin/audit-retention/stats',
    AUDIT_RETENTION_PURGE: '/admin/audit-retention/purge',
    RBAC_MATRIX: '/admin/rbac/matrix',
    STAFF: '/admin/staff',
    STAFF_PERMISSIONS_CATALOG: '/admin/staff/permissions-catalog',
    STAFF_BY_ID: (id: string) => `/admin/staff/${id}`,
    PERMISSION_PRESETS: '/admin/permission-presets',
    ECOSYSTEM_USERS: '/admin/ecosystem-users',
    ECOSYSTEM_USERS_META: '/admin/ecosystem-users/meta',
    ECOSYSTEM_USERS_STATUS: (id: string) => `/admin/ecosystem-users/${id}/status`,
    ECOSYSTEM_CORPORATES: '/admin/ecosystem-users/corporates',
    ECOSYSTEM_ENROLLMENTS: (corporateId: string) =>
      `/admin/ecosystem-users/corporates/${corporateId}/enrollments`,
    ECOSYSTEM_INSURANCE_CLAIMS: '/admin/ecosystem-users/insurance/claims',
    PORTAL_USERS: '/admin/portal-users',
    PORTAL_USERS_META: '/admin/portal-users/meta',
    PORTAL_USER_STATUS: (id: string) => `/admin/portal-users/${id}/status`,
    CONSUMER_SUPPORT: (id: string) => `/admin/consumers/${id}/support`,
    CONSUMER_SUPPORT_NOTES: (id: string) => `/admin/consumers/${id}/support-notes`,
    DISEASES: '/admin/diseases',
    DISEASES_LIST: '/admin/diseases/list',
    DISEASE_CATEGORIES: '/admin/diseases/categories',
    DISEASES_SYNC_CATALOG: '/admin/diseases/sync-catalog',
    DISEASES_RECONCILE_OPTIONS: '/admin/diseases/reconcile-options',
    DISEASE_PUBLIC_PAGE: (id: string) => `/admin/diseases/${id}/public-page`,
    LOCATION_FEES: '/admin/pricing/location-fees',
    BILLING_PLANS: '/admin/billing/plans',
    HOPE_HUB_MEDIA: '/admin/hope-hub/media',
    HOPE_HUB_OFFERINGS: '/admin/hope-hub/offerings',
    HOPE_HUB_OFFERING_BY_ID: (id: string) => `/admin/hope-hub/offerings/${id}`,
    HOPE_HUB_BANNERS: '/admin/hope-hub/banners',
    HOPE_HUB_BANNER_BY_ID: (id: string) => `/admin/hope-hub/banners/${id}`,
    HOPE_HUB_ORGANIZATION_LEADS: '/admin/hope-hub/organization-leads',
    HOPE_HUB_ORGANIZATION_LEAD_BY_ID: (id: string) => `/admin/hope-hub/organization-leads/${id}`,
    LISTENER_SCREENING: '/admin/hope-hub/listener-screening',
    LISTENER_SCREENING_BY_ID: (id: string) => `/admin/hope-hub/listener-screening/${id}`,
    LISTENER_SCREENING_PUBLISH: (id: string) => `/admin/hope-hub/listener-screening/${id}/publish`,
    HOPE_HUB_LIVE_GROUP_REPORTS: '/admin/hope-hub/live-group-reports',
    HOPE_HUB_LIVE_GROUP_REPORT_REVIEW: (id: string) =>
      `/admin/hope-hub/live-group-reports/${id}/review`,
    ASSESSMENT_DEFINITIONS: '/admin/assessment-definitions',
    ASSESSMENT_ACCESS_REPORT: '/admin/assessment-definitions/access-report',
    ASSESSMENT_DEFINITION_BY_ID: (id: string) => `/admin/assessment-definitions/${id}`,
    ASSESSMENT_DEFINITION_PUBLISH: (id: string) => `/admin/assessment-definitions/${id}/publish`,
    ASSESSMENT_DEFINITION_UNPUBLISH: (id: string) =>
      `/admin/assessment-definitions/${id}/unpublish`,
    PRACTICES: '/admin/practices',
    PRACTICE_BY_ID: (id: string) => `/admin/practices/${id}`,
    PRACTICE_RULES: '/admin/practice-rules',
    PRACTICE_RULE_BY_ID: (id: string) => `/admin/practice-rules/${id}`,
    LIFESTYLE_TIPS: '/admin/lifestyle-tips',
    LIFESTYLE_TIP_BY_ID: (id: string) => `/admin/lifestyle-tips/${id}`,
    LIFESTYLE_TIP_RULES: '/admin/lifestyle-tip-rules',
    LIFESTYLE_TIP_RULE_BY_ID: (id: string) => `/admin/lifestyle-tip-rules/${id}`,
    VACANCIES: '/admin/vacancies',
    VACANCY_BY_ID: (id: string) => `/admin/vacancies/${id}`,
    COUNSELLOR_APPLICATIONS: '/admin/counsellor-applications',
    COUNSELLOR_APPLICATION_STATUS: (id: string) => `/admin/counsellor-applications/${id}/status`,
    COUNSELLOR_APPLICATION_ONBOARD: (id: string) => `/admin/counsellor-applications/${id}/onboard`,
    CARE_CONTRIBUTOR_STATUS: (id: string) => `/admin/care-contributors/${id}/status`,
    SITE_CONFIG: '/admin/site-config',
    TESTIMONIALS: '/admin/testimonials',
    TESTIMONIAL_BY_ID: (id: string) => `/admin/testimonials/${id}`,
    FAQ: '/admin/faq',
    FAQ_BY_ID: (id: string) => `/admin/faq/${id}`,
    BLOG: '/admin/blog',
    BLOG_STATS: '/admin/blog/stats',
    BLOG_BY_ID: (id: string) => `/admin/blog/${id}`,
    BLOG_COMMENTS: '/admin/blog/comments',
    BLOG_COMMENT_BY_ID: (id: string) => `/admin/blog/comments/${id}`,
    ONLINE_DOCTORS: '/admin/online-doctors',
    ONLINE_DOCTORS_STATS: '/admin/online-doctors/stats',
    CHAT_SESSIONS: '/admin/chat-sessions',
    CHAT_SESSION_STATS: '/admin/chat-sessions/stats',
    CHAT_SESSION_BY_ID: (id: string) => `/admin/chat-sessions/${id}`,
    CHAT_SESSION_RESOLVE: (id: string) => `/admin/chat-sessions/${id}/resolve`,
    CHAT_SESSION_MESSAGE: (id: string) => `/admin/chat-sessions/${id}/message`,
    VISITOR_LEADS: '/admin/visitor-leads',
    VISITOR_LEAD_STATS: '/admin/visitor-leads/stats',
    VISITOR_LEAD_META: '/admin/visitor-leads/meta',
    VISITOR_LEAD_BY_ID: (id: string) => `/admin/visitor-leads/${id}`,
    VISITOR_LEAD_FOLLOW_UP: (id: string) => `/admin/visitor-leads/${id}/follow-up`,
    VISITOR_LEAD_ASSIGNABLE_PROVIDERS: '/admin/visitor-leads/assignable-providers',
    VISITOR_LEAD_ASSIGN: (id: string) => `/admin/visitor-leads/${id}/assign`,
    VISITOR_LEAD_ASSIGNMENT_CANCEL: (id: string) => `/admin/visitor-leads/assignments/${id}/cancel`,
    VISITOR_LEAD_BOOK: (id: string) => `/admin/visitor-leads/${id}/book-consultation`,
    VISITOR_LEAD_EXPORT: '/admin/visitor-leads/export',
    LEAD_FUNNEL: '/admin/analytics/lead-funnel',
    SALARY_EMPLOYEES: '/admin/salary/employees',
    SALARY_BY_EMPLOYEE: (empType: string, id: string) => `/admin/salary/${empType}/${id}`,
    REWARD_RULES: '/admin/rewards/rules',
    REWARD_RULE_BY_ID: (id: string) => `/admin/rewards/rules/${id}`,
    REWARD_REFERRALS: '/admin/rewards/referrals',
    REWARD_WALLET: (patientId: string) => `/admin/rewards/wallet/${patientId}`,
    REWARD_WALLET_ADJUST: (patientId: string) => `/admin/rewards/wallet/${patientId}/adjust`,
    CLINICAL_METHOD_OPTIONS: CROSS_APP_API_PATHS.ADMIN.CLINICAL_METHOD_OPTIONS,
    PRESCRIPTIONS: CROSS_APP_API_PATHS.ADMIN.PRESCRIPTIONS,
    PRESCRIPTION_BY_ID: CROSS_APP_API_PATHS.ADMIN.PRESCRIPTION_BY_ID,
    CASE_ANALYSES: CROSS_APP_API_PATHS.ADMIN.CASE_ANALYSES,
    CASE_ANALYSIS_BY_ID: CROSS_APP_API_PATHS.ADMIN.CASE_ANALYSIS_BY_ID,
    PATIENT_CLINICAL_MEDIA: CROSS_APP_API_PATHS.ADMIN.PATIENT_CLINICAL_MEDIA,
    FINANCE: {
      SUMMARY: '/admin/finance/summary',
      REVENUE_TREND: '/admin/finance/revenue/trend',
      REVENUE_BY_DOCTOR: '/admin/finance/revenue/by-doctor',
      REVENUE_BY_DISEASE: '/admin/finance/revenue/by-disease',
      MEDICINE_REVENUE: '/admin/finance/medicine-revenue',
      OUTSTANDING: '/admin/finance/outstanding',
      PAYSLIP: (type: string, id: string) => `/admin/finance/payslip/${type}/${id}`,
      EXPENSES: '/admin/finance/expenses',
      EXPENSES_SUMMARY: '/admin/finance/expenses/summary',
      BRANCHES: '/admin/finance/branches',
      EXPORT_BUNDLE: '/admin/finance/export-bundle',
      PERIOD_REPORT: '/admin/finance/period-report',
      PROVIDER_PAYOUTS: '/admin/finance/provider-payouts',
      PROVIDER_PAYOUT: (id: string) => `/admin/finance/provider-payouts/${id}`,
      PROVIDER_PAYOUT_BACKFILL: '/admin/finance/provider-payouts/backfill',
    },
  },
  CONSULTATIONS: '/consultations',
  HR: {
    DASHBOARD: '/hr/dashboard',
    DOCTORS: '/hr/doctors',
    USERS: '/hr/users',
    EMPLOYEES: '/hr/employees',
    LEAVES: '/hr/leaves',
    STORES: '/hr/stores',
    STORE_STAFF: '/hr/store/staff',
    STORE_STAFF_STATUS: (id: string) => `/hr/store/staff/${id}/status`,
    PAYROLL: '/hr/payroll',
  },
} as const;

export const API_EXPORT_FORMAT = {
  CSV: 'csv',
} as const;
