export const API_PATHS = {
  AUTH: {
    STAFF_LOGIN: '/auth/staff-login',
    ME: '/me'
  },
  ADMIN: {
    REPORTS: '/admin/reports',
    AUDIT_LOGS: '/admin/audit-logs',
    ADMINS: '/admin/admins',
    ADMIN_STATUS: (id: string) => `/admin/admins/${id}/status`,
    CONSULTATION_STATUS: (id: string) => `/admin/consultations/${id}/status`,
    ADHERENCE_RISK: '/admin/adherence/risk-cohorts',
    ANALYTICS_FUNNELS: '/admin/analytics/funnels',
    PAYMENTS: '/admin/payments',
    DOCTORS: '/admin/doctors',
    DOCTORS_PENDING: '/admin/doctors/pending',
    CONSUMERS: '/admin/consumers',
    PATIENTS_SEARCH: '/admin/patients/search',
    PATIENTS: '/admin/patients',
    PURCHASE_ORDERS: '/admin/purchase-orders',
    SUPPLIERS: '/admin/suppliers',
    MEDICINES: '/admin/medicines',
    INVENTORY_OVERVIEW: '/admin/inventory/overview',
    INVENTORY_STORE_STOCK: (storeId: string) => `/admin/inventory/stores/${storeId}/stock`,
    NOTIFICATION_TEMPLATES: '/admin/notifications/templates',
    NOTIFICATION_BROADCAST: '/admin/notifications/broadcast',
    NOTIFICATION_BROADCASTS: '/admin/notifications/broadcasts',
    AUDIT_RETENTION_STATS: '/admin/audit-retention/stats',
    AUDIT_RETENTION_PURGE: '/admin/audit-retention/purge',
    RBAC_MATRIX: '/admin/rbac/matrix',
    STAFF: '/admin/staff',
    STAFF_PERMISSIONS_CATALOG: '/admin/staff/permissions-catalog',
    STAFF_BY_ID: (id: string) => `/admin/staff/${id}`,
    PERMISSION_PRESETS: '/admin/permission-presets',
    ECOSYSTEM_USERS: '/admin/ecosystem-users',
    ECOSYSTEM_USERS_META: '/admin/ecosystem-users/meta',
    ECOSYSTEM_USERS_STATUS: (id: string) => `/admin/ecosystem-users/${id}/status`,
    ECOSYSTEM_CORPORATES: '/admin/ecosystem-users/corporates',
    ECOSYSTEM_ENROLLMENTS: (corporateId: string) => `/admin/ecosystem-users/corporates/${corporateId}/enrollments`,
    ECOSYSTEM_INSURANCE_CLAIMS: '/admin/ecosystem-users/insurance/claims',
    PORTAL_USERS: '/admin/portal-users',
    PORTAL_USERS_META: '/admin/portal-users/meta',
    PORTAL_USER_STATUS: (id: string) => `/admin/portal-users/${id}/status`,
    CONSUMER_SUPPORT: (id: string) => `/admin/consumers/${id}/support`,
    CONSUMER_SUPPORT_NOTES: (id: string) => `/admin/consumers/${id}/support-notes`,
    DISEASES: '/admin/diseases',
    DISEASES_LIST: '/admin/diseases/list',
    VACANCIES: '/admin/vacancies',
    VACANCY_BY_ID: (id: string) => `/admin/vacancies/${id}`,
    SITE_CONFIG: '/admin/site-config',
    TESTIMONIALS: '/admin/testimonials',
    TESTIMONIAL_BY_ID: (id: string) => `/admin/testimonials/${id}`,
    FAQ: '/admin/faq',
    FAQ_BY_ID: (id: string) => `/admin/faq/${id}`,
    BLOG: '/admin/blog',
    BLOG_BY_ID: (id: string) => `/admin/blog/${id}`,
    CHAT_SESSIONS: '/admin/chat-sessions',
    CHAT_SESSION_STATS: '/admin/chat-sessions/stats',
    CHAT_SESSION_BY_ID: (id: string) => `/admin/chat-sessions/${id}`,
    CHAT_SESSION_RESOLVE: (id: string) => `/admin/chat-sessions/${id}/resolve`,
    CHAT_SESSION_MESSAGE: (id: string) => `/admin/chat-sessions/${id}/message`,
    VISITOR_LEADS: '/admin/visitor-leads',
    VISITOR_LEAD_STATS: '/admin/visitor-leads/stats',
    VISITOR_LEAD_META: '/admin/visitor-leads/meta',
    VISITOR_LEAD_BY_ID: (id: string) => `/admin/visitor-leads/${id}`,
    VISITOR_LEAD_FOLLOW_UP: (id: string) => `/admin/visitor-leads/${id}/follow-up`,
    VISITOR_LEAD_BOOK: (id: string) => `/admin/visitor-leads/${id}/book-consultation`,
    VISITOR_LEAD_EXPORT: '/admin/visitor-leads/export',
    LEAD_FUNNEL: '/admin/analytics/lead-funnel',
    SALARY_EMPLOYEES: '/admin/salary/employees',
    SALARY_BY_EMPLOYEE: (empType: string, id: string) => `/admin/salary/${empType}/${id}`,
    FINANCE: {
      SUMMARY: '/admin/finance/summary',
      REVENUE_TREND: '/admin/finance/revenue/trend',
      REVENUE_BY_DOCTOR: '/admin/finance/revenue/by-doctor',
      REVENUE_BY_DISEASE: '/admin/finance/revenue/by-disease',
      MEDICINE_REVENUE: '/admin/finance/medicine-revenue',
      OUTSTANDING: '/admin/finance/outstanding',
      PAYSLIP: (type: string, id: string) => `/admin/finance/payslip/${type}/${id}`,
      EXPENSES: '/admin/finance/expenses',
      EXPENSES_SUMMARY: '/admin/finance/expenses/summary',
      BRANCHES: '/admin/finance/branches',
      EXPORT_BUNDLE: '/admin/finance/export-bundle',
      PERIOD_REPORT: '/admin/finance/period-report'
    }
  },
  CONSULTATIONS: '/consultations',
  HR: {
    DOCTORS: '/hr/doctors',
    USERS: '/hr/users',
    EMPLOYEES: '/hr/employees',
    LEAVES: '/hr/leaves',
    STORES: '/hr/stores',
    STORE_STAFF: '/hr/store/staff',
    STORE_STAFF_STATUS: (id: string) => `/hr/store/staff/${id}/status`,
    PAYROLL: '/hr/payroll'
  }
} as const;

export const API_EXPORT_FORMAT = {
  CSV: 'csv'
} as const;
