UPDATE "RewardProgramRule"
SET
  "code" = 'FIRSTTALK1_LISTENER_TEST',
  "name" = 'First Talk ₹1 listener test',
  "description" = 'Test coupon that lets patients book listener support for ₹1 any number of times.',
  "kind" = 'PROMO',
  "trigger" = 'CONSULTATION_PAID',
  "beneficiary" = 'PAYING_PATIENT',
  "valueType" = 'CHECKOUT_DISCOUNT_PERCENT',
  "valueAmount" = 10000,
  "appliesTo" = 'CONSULTATION',
  "maxUsesPerPatient" = NULL,
  "maxUsesGlobal" = NULL,
  "maxDiscountInPaise" = NULL,
  "minOrderInPaise" = NULL,
  "minPayableInPaise" = 100,
  "validFrom" = NULL,
  "validUntil" = NULL,
  "isActive" = true,
  "priority" = 100,
  "conditions" = '{"targetPayableInPaise":100,"providerCareTeamTypes":["PEER_SUPPORT_VOLUNTEER","PSYCHOLOGY_STUDENT_VOLUNTEER"]}'::jsonb,
  "updatedAt" = CURRENT_TIMESTAMP
WHERE "promoCode" = 'FIRSTTALK1';

INSERT INTO "RewardProgramRule" (
  "id",
  "code",
  "name",
  "description",
  "kind",
  "trigger",
  "beneficiary",
  "valueType",
  "valueAmount",
  "appliesTo",
  "promoCode",
  "maxUsesPerPatient",
  "maxUsesGlobal",
  "maxDiscountInPaise",
  "minOrderInPaise",
  "minPayableInPaise",
  "validFrom",
  "validUntil",
  "isActive",
  "priority",
  "conditions",
  "createdAt",
  "updatedAt"
)
SELECT
  'reward_firsttalk1_listener_1',
  'FIRSTTALK1_LISTENER_TEST',
  'First Talk ₹1 listener test',
  'Test coupon that lets patients book listener support for ₹1 any number of times.',
  'PROMO',
  'CONSULTATION_PAID',
  'PAYING_PATIENT',
  'CHECKOUT_DISCOUNT_PERCENT',
  10000,
  'CONSULTATION',
  'FIRSTTALK1',
  NULL,
  NULL,
  NULL,
  NULL,
  100,
  NULL,
  NULL,
  true,
  100,
  '{"targetPayableInPaise":100,"providerCareTeamTypes":["PEER_SUPPORT_VOLUNTEER","PSYCHOLOGY_STUDENT_VOLUNTEER"]}'::jsonb,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
WHERE NOT EXISTS (
  SELECT 1 FROM "RewardProgramRule"
  WHERE "code" = 'FIRSTTALK1_LISTENER_TEST'
     OR "promoCode" = 'FIRSTTALK1'
)
ON CONFLICT ("code") DO UPDATE SET
  "name" = EXCLUDED."name",
  "description" = EXCLUDED."description",
  "kind" = EXCLUDED."kind",
  "trigger" = EXCLUDED."trigger",
  "beneficiary" = EXCLUDED."beneficiary",
  "valueType" = EXCLUDED."valueType",
  "valueAmount" = EXCLUDED."valueAmount",
  "appliesTo" = EXCLUDED."appliesTo",
  "promoCode" = EXCLUDED."promoCode",
  "maxUsesPerPatient" = EXCLUDED."maxUsesPerPatient",
  "maxUsesGlobal" = EXCLUDED."maxUsesGlobal",
  "maxDiscountInPaise" = EXCLUDED."maxDiscountInPaise",
  "minOrderInPaise" = EXCLUDED."minOrderInPaise",
  "minPayableInPaise" = EXCLUDED."minPayableInPaise",
  "validFrom" = EXCLUDED."validFrom",
  "validUntil" = EXCLUDED."validUntil",
  "isActive" = EXCLUDED."isActive",
  "priority" = EXCLUDED."priority",
  "conditions" = EXCLUDED."conditions",
  "updatedAt" = CURRENT_TIMESTAMP;
