import { Router } from 'express';
import type { Server as SocketIoServer } from 'socket.io';
import { registerAdminAuditRoutes } from './audit.js';
import { registerAdminConsultationRoutes } from './consultations.js';
import { registerAdminConsumerRoutes } from './consumers.js';
import { registerAdminDoctorRoutes } from './doctors.js';
import { registerAdminPaymentRoutes } from './payments.js';
import { registerAdminReportRoutes } from './reports.js';
import { registerAdminPatientLookupRoutes } from '../store/patients.js';
import { registerAdminSupportRoutes } from './support.js';
import { registerAdminAdherenceRoutes } from './adherence.js';
import { registerAdminAnalyticsRoutes } from '../analytics.js';
import { registerAdminPurchaseOrderRoutes } from './purchase-orders.js';
import { registerAdminCatalogOpsRoutes } from './catalog-ops.js';
import { registerAdminUserRoutes } from './admins.js';
import { registerAdminLabReferralRoutes } from './lab-referrals.js';
import { registerAdminInventoryRoutes } from './inventory.js';
import { registerAdminNotificationRoutes } from './notifications.js';
import { registerAdminRbacRoutes } from './rbac.js';
import { registerAdminEcosystemUserRoutes } from './ecosystem-users.js';
import { registerAdminPortalUserRoutes } from './portal-users.js';
import { registerAdminStaffRoutes } from './admin-staff.routes.js';
import { registerAdminPermissionPresetRoutes } from './admin-permission-presets.routes.js';
import { registerAdminVacancyRoutes } from './vacancies.js';
import { registerAdminSiteConfigRoutes } from './site-config.js';
import { registerAdminTestimonialRoutes } from './testimonials.js';
import { registerAdminFaqRoutes } from './faq.js';
import { registerAdminBlogRoutes } from './blog.js';
import { registerAdminChatRoutes } from './chat.js';
import { registerAdminVisitorLeadRoutes } from './visitor-leads.js';
import { registerAdminSalaryRoutes } from './salary.routes.js';
import { registerAdminPricingRoutes } from './pricing.routes.js';
import { registerAdminRewardsRoutes } from './rewards.js';
import { registerAdminClinicalRecordsRoutes } from './clinical-records.js';
import { adminPermissionMiddleware } from '../../admin-route-permissions.js';

export function createAdminRouter(io: SocketIoServer) {
  const router = Router();

  router.use(adminPermissionMiddleware);

  registerAdminDoctorRoutes(router);
  registerAdminConsumerRoutes(router);
  registerAdminSupportRoutes(router);
  registerAdminAdherenceRoutes(router);
  registerAdminAnalyticsRoutes(router);
  registerAdminAuditRoutes(router);
  registerAdminConsultationRoutes(router, io);
  registerAdminPaymentRoutes(router);
  registerAdminReportRoutes(router);
  registerAdminPatientLookupRoutes(router);
  registerAdminPurchaseOrderRoutes(router);
  registerAdminCatalogOpsRoutes(router);
  registerAdminUserRoutes(router);
  registerAdminLabReferralRoutes(router);
  registerAdminInventoryRoutes(router);
  registerAdminNotificationRoutes(router);
  registerAdminRbacRoutes(router);
  registerAdminEcosystemUserRoutes(router);
  registerAdminPortalUserRoutes(router);
  registerAdminStaffRoutes(router);
  registerAdminPermissionPresetRoutes(router);
  registerAdminVacancyRoutes(router);
  registerAdminSiteConfigRoutes(router);
  registerAdminTestimonialRoutes(router);
  registerAdminFaqRoutes(router);
  registerAdminBlogRoutes(router);
  registerAdminChatRoutes(router);
  registerAdminVisitorLeadRoutes(router);
  registerAdminSalaryRoutes(router);
  registerAdminPricingRoutes(router);
  registerAdminRewardsRoutes(router);
  registerAdminClinicalRecordsRoutes(router);

  return router;
}
