INSERT INTO "SiteConfig" ("key", "value", "label", "updatedAt") VALUES
  ('telegramGroupHelpBotUsername', 'Hopehubbot', 'Group Help bot username', NOW()),
  ('telegramGroupHelpGroupChatId', '', 'Telegram group chat ID', NOW()),
  ('telegramGroupHelpGroupTitle', 'Hope Hub Group Help', 'Group title', NOW()),
  ('telegramGroupHelpWelcomeMessage', 'Welcome to Hope Hub. This is a safe, respectful space for emotional support. Please read the rules, protect privacy, and avoid sharing emergency situations here.', 'Welcome message', NOW()),
  ('telegramGroupHelpRulesMessage', 'Group rules:\n1. Be kind and respectful.\n2. Do not share anyone’s private information.\n3. No diagnosis, medical claims, spam, promotions, or harassment.\n4. If you are in immediate danger, contact local emergency services.', 'Rules message', NOW()),
  ('telegramGroupHelpSupportMessage', 'If you need one-to-one support, visit https://hopehub.in or use the Hope Hub web bot. For emergencies, please contact local emergency services or a crisis helpline.', 'Support message', NOW()),
  ('telegramGroupHelpPinnedMessage', 'Hope Hub group guide: keep conversations gentle, anonymous-friendly, and respectful. For private support, use https://hopehub.in.', 'Pinned intro message', NOW()),
  ('telegramGroupHelpRecurringMessage', 'Gentle reminder: this group is for peer support and community care. Please keep details private and reach out for professional help when needed.', 'Recurring reminder message', NOW()),
  ('telegramGroupHelpCrisisMessage', 'If you may hurt yourself or someone else, please contact local emergency services now. Hope Hub group chat is not an emergency service.', 'Crisis escalation message', NOW()),
  ('telegramGroupHelpCaptchaMode', 'on', 'Captcha mode', NOW()),
  ('telegramGroupHelpWarnLimit', '3', 'Warning limit', NOW()),
  ('telegramGroupHelpLinkPolicy', 'warn', 'Link policy', NOW()),
  ('telegramGroupHelpBannedWords', '', 'Banned words / phrases', NOW()),
  ('telegramGroupHelpAdminNotes', 'GroupHelp controls the bot runtime. Do not set HopeHub API webhook for @Hopehubbot.', 'Admin notes', NOW()),
  ('telegramGroupHelpWelcomeCommandTemplate', '/welcome {message}', 'Welcome command template', NOW()),
  ('telegramGroupHelpRulesCommandTemplate', '/rules {message}', 'Rules command template', NOW()),
  ('telegramGroupHelpSupportCommandTemplate', '/setcmd support {message}', 'Support command template', NOW()),
  ('telegramGroupHelpPinnedCommandTemplate', '/pin {message}', 'Pinned intro command template', NOW()),
  ('telegramGroupHelpRecurringCommandTemplate', '/recurring {message}', 'Recurring reminder command template', NOW()),
  ('telegramGroupHelpCaptchaCommandTemplate', '/captcha {value}', 'Captcha command template', NOW()),
  ('telegramGroupHelpWarnLimitCommandTemplate', '/warnlimit {value}', 'Warning limit command template', NOW()),
  ('telegramGroupHelpLinkPolicyCommandTemplate', '/links {value}', 'Link policy command template', NOW()),
  ('telegramGroupHelpBannedWordsCommandTemplate', '/filter {lines}', 'Banned words command template', NOW())
ON CONFLICT ("key") DO NOTHING;
