export const CONSUMER_UX_COPY = {
  cta: {
    talkNow: 'Talk to a caring listener',
    bookSupport: 'Book support',
    startTest: 'Start a test',
    meetCareTeam: 'Meet care team',
    exploreSupportOptions: 'Explore support options',
    seeCommunitySupport: 'See community support',
  },
  supportPath: {
    chooserAria: 'Choose support path',
    chooserEyebrow: 'Choose support path',
    chooserTitle: 'What kind of help feels right?',
    chooserHint: 'This helps us show suitable support. You can change it before checkout.',
    genericRouteText: 'support path',
  },
  service: {
    privateOneToOne: 'Private 1:1',
    privateOneToOneCare: 'Private 1:1 care',
    privateSupport: 'private support',
    guidedMatching: 'Help choosing at checkout',
    supportOptionsTitle: 'Expert support options',
  },
  booking: {
    pageTitle: 'Book support',
    formAria: 'Support booking form',
    successTitle: 'Support request sent.',
    creating: 'Confirming your booking...',
    reviewRequest: 'We review your request',
    fallbackOption: 'available time',
  },
  assessment: {
    nextTitle: 'What would help next?',
    nextCopy:
      'You can start gently. Talk now if someone is live, book structured support, or use self-help resources at your pace.',
  },
  messages: {
    authRequiredLive: 'Sign up or log in to start a live session.',
    authRequiredPayment: 'Sign up or log in to continue to secure payment.',
    authRequiredCoupon: 'Sign up or log in to validate this coupon.',
    signInBeforeCoupon: 'Please sign in before applying a coupon.',
    signInBeforePayment: 'Please sign in before payment.',
    providerNotLiveBook:
      'This person is not live right now. Choose a time and we will help you connect.',
    modeUnavailableBook: (_mode: string) =>
      `A live connection is not available right now. Choose a time instead.`,
    noLiveExpertBook: 'No matching expert is live right now. Choose a slot instead.',
    noLiveExpertTitle: 'No matching expert is live right now',
    noLiveExpertServiceFallback:
      'You can book a time, meet the care team, or join the community chat.',
    noLiveExpertAssessmentFallback:
      'Your result is saved. You can book a time or meet care-team members suited to your needs.',
    liveSessionConfirmed: 'Live session confirmed. Opening your session room.',
    quickTalkConfirmed: 'Your live session is ready. Open your dashboard to join.',
    supportChatCreated: 'Support chat created.',
    liveConnectSlow: 'This is taking longer than usual. Please try again in a moment.',
    couldNotStartLive: 'Could not start this live session right now.',
    couponInvalid: 'Enter a valid coupon code.',
    couponSaved: 'Coupon saved for checkout.',
    couponApplied: 'Coupon applied.',
    couponDiscountApplied: 'Discount coupon applied.',
    couponNoDiscount: 'No discount applies to this checkout.',
    couponNoDiscountForCheckout: 'No coupon discount applies to this checkout.',
    couponCouldNotApply: 'Coupon could not be applied.',
    couponCouldNotApplyShort: 'Could not apply coupon.',
    testAlreadyUnlocked: 'This test is already unlocked.',
    testCouponUnlocked: 'Coupon applied. Test unlocked.',
    testPaymentUnlocked: 'Payment verified. Test unlocked.',
    paymentCouldNotComplete: 'Payment could not be completed.',
    unexpectedError: 'An unexpected error occurred. Please try again.',
  },
} as const;
