INSERT INTO "SiteConfig" ("key", "value", "label", "updatedAt") VALUES
  ('doctorListLimit', '12', 'Doctor list limit', NOW()),
  ('whatsappPhone', '919876543210', 'WhatsApp phone number', NOW()),
  ('whatsappGroupUrl', 'https://chat.whatsapp.com/CbbNoo5kXw3FWWKTGO82kz', 'WhatsApp group link', NOW()),
  ('whatsappGroupLabel', 'Join WhatsApp group', 'WhatsApp button label', NOW()),
  ('telegramUsername', 'hopehubindia', 'Telegram public username', NOW()),
  ('telegramUserBotUsername', 'Hopehubbot', 'Telegram user bot username', NOW()),
  ('telegramDoctorBotUsername', 'Hopehubprovidersbot', 'Telegram care team bot username', NOW()),
  ('telegramAdminBotUsername', 'Hopehuboperationbot', 'Telegram admin bot username', NOW()),
  ('telegramQrCodePath', 'https://hopehub-public-assets-924479393196.s3.us-east-1.amazonaws.com/qr/telegram/hopehubindiaqr.jpg', 'Telegram QR image path', NOW()),
  ('whatsappQrCodePath', 'https://hopehub-public-assets-924479393196.s3.us-east-1.amazonaws.com/qr/whatsapp/whatsapp-qr.jpeg', 'WhatsApp QR image path', NOW()),
  ('telegramDefaultOfferingSlug', 'single-30-minute-session', 'Telegram default paid offering', NOW()),
  ('clinicName', 'HopeHub Care and Research Centre', 'Clinic name', NOW()),
  ('statConsultations', '5,000+', 'Stat: consultations completed', NOW()),
  ('statDoctors', '12+', 'Stat: number of doctors', NOW()),
  ('statRating', '4.8★', 'Stat: patient rating', NOW()),
  ('statFollowUp', '92%', 'Stat: follow-up compliance', NOW()),
  ('statPatientsTreated', '4,800+', 'Testimonials: patients treated', NOW()),
  ('statConditionsTreated', '15+', 'Testimonials: conditions treated', NOW()),
  ('statImprovement', '92%', 'Testimonials: improvement rate', NOW()),
  ('statSatisfaction', '4.8 / 5', 'Testimonials: satisfaction score', NOW()),
  ('contactPhone', '+91-98765-43210', 'Contact phone (display)', NOW()),
  ('contactPhoneTel', '+919876543210', 'Contact phone (tel link)', NOW()),
  ('contactEmail', 'contact@hopehub.in', 'Contact email', NOW()),
  ('clinicAddressLine1', 'Ranchi Main Clinic', 'Address line 1', NOW()),
  ('clinicAddressLine2', 'Near City Centre, Main Road', 'Address line 2', NOW()),
  ('clinicAddressLine3', 'Ranchi, Jharkhand, India', 'Address line 3', NOW()),
  ('clinicAddressLine4', 'Pincode — 834001', 'Address line 4', NOW()),
  ('homeHeroEyebrow', 'Doctor-led homeopathy', 'Home hero eyebrow', NOW()),
  ('homeHeroHeadline', 'Personalised homeopathic care for every health concern.', 'Home hero headline', NOW()),
  ('homeHeroLead', 'Acute illnesses, chronic conditions, skin and hair issues, digestive problems, allergies, mental wellness, and more — consult qualified homeopathic doctors online with prescriptions and follow-up.', 'Home hero lead text', NOW())
ON CONFLICT ("key") DO NOTHING;
