UPDATE "RewardProgramRule"
SET
  "code" = 'FIRSTCHAT_LISTENER_FREE',
  "name" = 'First Chat free listener session',
  "description" = 'Reusable test coupon for a fully free listener support session.',
  "kind" = 'PROMO',
  "trigger" = 'CONSULTATION_PAID',
  "beneficiary" = 'PAYING_PATIENT',
  "valueType" = 'CHECKOUT_DISCOUNT_PERCENT',
  "valueAmount" = 10000,
  "appliesTo" = 'CONSULTATION',
  "maxUsesPerPatient" = NULL,
  "maxUsesGlobal" = NULL,
  "maxDiscountInPaise" = NULL,
  "minOrderInPaise" = NULL,
  "minPayableInPaise" = 0,
  "validFrom" = NULL,
  "validUntil" = NULL,
  "isActive" = true,
  "priority" = 110,
  "conditions" = '{"targetPayableInPaise":0,"providerCareTeamTypes":["PEER_SUPPORT_VOLUNTEER","PSYCHOLOGY_STUDENT_VOLUNTEER"],"showToConsumers":false,"featured":false}'::jsonb,
  "updatedAt" = CURRENT_TIMESTAMP
WHERE "promoCode" = 'FIRSTCHAT';

INSERT INTO "RewardProgramRule" (
  "id",
  "code",
  "name",
  "description",
  "kind",
  "trigger",
  "beneficiary",
  "valueType",
  "valueAmount",
  "appliesTo",
  "promoCode",
  "maxUsesPerPatient",
  "maxUsesGlobal",
  "maxDiscountInPaise",
  "minOrderInPaise",
  "minPayableInPaise",
  "validFrom",
  "validUntil",
  "isActive",
  "priority",
  "conditions",
  "createdAt",
  "updatedAt"
)
SELECT
  'reward_firstchat_listener_free',
  'FIRSTCHAT_LISTENER_FREE',
  'First Chat free listener session',
  'Reusable test coupon for a fully free listener support session.',
  'PROMO',
  'CONSULTATION_PAID',
  'PAYING_PATIENT',
  'CHECKOUT_DISCOUNT_PERCENT',
  10000,
  'CONSULTATION',
  'FIRSTCHAT',
  NULL,
  NULL,
  NULL,
  NULL,
  0,
  NULL,
  NULL,
  true,
  110,
  '{"targetPayableInPaise":0,"providerCareTeamTypes":["PEER_SUPPORT_VOLUNTEER","PSYCHOLOGY_STUDENT_VOLUNTEER"],"showToConsumers":false,"featured":false}'::jsonb,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
WHERE NOT EXISTS (
  SELECT 1
  FROM "RewardProgramRule"
  WHERE "code" = 'FIRSTCHAT_LISTENER_FREE' OR "promoCode" = 'FIRSTCHAT'
)
ON CONFLICT ("code") DO UPDATE SET
  "name" = EXCLUDED."name",
  "description" = EXCLUDED."description",
  "kind" = EXCLUDED."kind",
  "trigger" = EXCLUDED."trigger",
  "beneficiary" = EXCLUDED."beneficiary",
  "valueType" = EXCLUDED."valueType",
  "valueAmount" = EXCLUDED."valueAmount",
  "appliesTo" = EXCLUDED."appliesTo",
  "promoCode" = EXCLUDED."promoCode",
  "maxUsesPerPatient" = EXCLUDED."maxUsesPerPatient",
  "maxUsesGlobal" = EXCLUDED."maxUsesGlobal",
  "maxDiscountInPaise" = EXCLUDED."maxDiscountInPaise",
  "minOrderInPaise" = EXCLUDED."minOrderInPaise",
  "minPayableInPaise" = EXCLUDED."minPayableInPaise",
  "validFrom" = EXCLUDED."validFrom",
  "validUntil" = EXCLUDED."validUntil",
  "isActive" = EXCLUDED."isActive",
  "priority" = EXCLUDED."priority",
  "conditions" = EXCLUDED."conditions",
  "updatedAt" = CURRENT_TIMESTAMP;
