BEGIN;

INSERT INTO "SiteConfig" ("key", "value", "label", "updatedAt")
VALUES (
  'telegramGroupHelpCustomReplies',
  $wellbeing$rose-filter:{"id":"hopehub-immediate-support-v1","category":"crisis","cooldownSeconds":1800,"notifyStaff":true,"triggers":[{"value":"suicide","mode":"contains"},{"value":"sucide","mode":"contains"},{"value":"suicde","mode":"contains"},{"value":"suicidal","mode":"contains"},{"value":"self harm","mode":"contains"},{"value":"self-harm","mode":"contains"},{"value":"kill myself","mode":"contains"},{"value":"end my life","mode":"contains"},{"value":"don't want to live","mode":"contains"},{"value":"dont want to live","mode":"contains"},{"value":"do not want to live","mode":"contains"},{"value":"want to die","mode":"contains"},{"value":"ending my life","mode":"contains"},{"value":"jeena nahi","mode":"contains"},{"value":"marna chahta","mode":"contains"},{"value":"marna chahti","mode":"contains"},{"value":"khud ko mar","mode":"contains"},{"value":"zindagi khatam","mode":"contains"}],"text":"{mention}, I’m really sorry you’re carrying this. If you may act now or are in immediate danger, call India’s emergency number *112* or go to the nearest emergency department. For 24/7 tele-mental-health support, call *Tele-MANAS at 14416* (or 1800-89-14416). If possible, stay with someone you trust and move away from anything you could use to hurt yourself. Hope Hub is not an emergency service.","media":{"type":"photo","fileId":"https://hopehub-public-assets-924479393196.s3.us-east-1.amazonaws.com/telegram/wellbeing/hopehub-immediate-support-v1.png"},"button":{"text":"Open Hope Hub support","url":"https://hopehub.in/#live-connect"},"audience":"all","allowBots":false}
rose-filter:{"id":"hopehub-anxiety-support-v1","category":"wellbeing","cooldownSeconds":1800,"triggers":[{"value":"panic attack","mode":"contains"},{"value":"anxiety attack","mode":"contains"},{"value":"severe anxiety","mode":"contains"},{"value":"panic ho raha","mode":"contains"},{"value":"panic ho rahi","mode":"contains"},{"value":"ghabrahat ho raha","mode":"contains"},{"value":"ghabrahat ho rahi","mode":"contains"},{"value":"can't breathe from anxiety","mode":"contains"},{"value":"cant breathe from anxiety","mode":"contains"},{"value":"cannot breathe from anxiety","mode":"contains"}],"text":"{mention}, pause with us for a moment. If it feels comfortable, breathe in gently for 4, hold for 4, and breathe out slowly for 6. Stop if this feels uncomfortable. You can ask for support below. If you have severe physical symptoms or are in immediate danger, contact emergency services.","media":{"type":"photo","fileId":"https://hopehub-public-assets-924479393196.s3.us-east-1.amazonaws.com/telegram/wellbeing/hopehub-anxiety-support-v1.png"},"button":{"text":"Ask for support","url":"https://hopehub.in/#live-connect"},"audience":"all","allowBots":false}
rose-filter:{"id":"hopehub-low-mood-support-v1","category":"wellbeing","cooldownSeconds":1800,"triggers":[{"value":"feeling depressed","mode":"contains"},{"value":"feel depressed","mode":"contains"},{"value":"feeling hopeless","mode":"contains"},{"value":"feel hopeless","mode":"contains"},{"value":"can't cope","mode":"contains"},{"value":"cant cope","mode":"contains"},{"value":"cannot cope","mode":"contains"},{"value":"no hope left","mode":"contains"},{"value":"bahut udaas","mode":"contains"},{"value":"koi umeed nahi","mode":"contains"}],"text":"{mention}, thank you for saying this. You don’t have to solve everything right now. Consider staying near someone you trust and taking one small next step. You can request support below. If you may harm yourself, call 112 or Tele-MANAS at 14416 now.","media":{"type":"photo","fileId":"https://hopehub-public-assets-924479393196.s3.us-east-1.amazonaws.com/telegram/wellbeing/hopehub-low-mood-support-v1.png"},"button":{"text":"Ask for support","url":"https://hopehub.in/#live-connect"},"audience":"all","allowBots":false}
rose-filter:{"id":"hopehub-loneliness-support-v1","category":"wellbeing","cooldownSeconds":1800,"triggers":[{"value":"feeling lonely","mode":"contains"},{"value":"i am lonely","mode":"contains"},{"value":"i'm lonely","mode":"contains"},{"value":"im lonely","mode":"contains"},{"value":"no one to talk to","mode":"contains"},{"value":"need someone to talk to","mode":"contains"},{"value":"feel alone","mode":"contains"},{"value":"akela feel","mode":"contains"},{"value":"akeli feel","mode":"contains"},{"value":"koi baat karne wala nahi","mode":"contains"}],"text":"{mention}, you’re welcome here. You can join the conversation at your own pace or request one-to-one support below. Please keep personal contact details private and use Hope Hub’s safe channels.","media":{"type":"photo","fileId":"https://hopehub-public-assets-924479393196.s3.us-east-1.amazonaws.com/telegram/wellbeing/hopehub-loneliness-support-v1.png"},"button":{"text":"Connect safely","url":"https://hopehub.in/#live-connect"},"audience":"all","allowBots":false}$wellbeing$,
  'Keyword replies and buttons',
  NOW()
)
ON CONFLICT ("key") DO UPDATE
SET "value" = CASE
      WHEN COALESCE(TRIM("SiteConfig"."value"), '') = '' THEN EXCLUDED."value"
      ELSE "SiteConfig"."value" || E'\n' || EXCLUDED."value"
    END,
    "updatedAt" = NOW()
WHERE POSITION('"id":"hopehub-immediate-support-v1"' IN "SiteConfig"."value") = 0;

COMMIT;
